sudo: false
language: ruby
rvm:
  - 2.2.3
before_script:
  - "ruby lib/initial_setup.rb ../.travis_setup"
  - "psql -c 'create database www_conductorproductions_com_test;' -U postgres"
  - "bundle exec rake db:migrate"
